# Generated by Django 6.1 on 2026-08-12 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="rental",
            table=None,
        ),
    ]
